#!/usr/bin/env node

var child_process = require('child_process');

function run() {
    child_process.execSync("node ./.src-dist/index.js", {stdio: 'inherit', cwd: __dirname});
}

function build() {
	child_process.execSync('node build', {stdio: 'inherit', cwd: __dirname});
}

try {
    build();
	run();
} catch(err) {
    if (err) throw err;
}